### ISSUE TITLE
解压预训练权重文件时报错

### ISSUE THREAD

**Issue by Alive1024** [Oneflow-Inc/vision#167]
使用 models 中的模型时，例如 ` model = vgg11(pretrained=True)` ，成功下载 zip 权重文件后，解压过程出错，导致解压中断、参数文件不完整。如果自行将下载的 zip 解压，就能正常使用。多个模型都有同样的问题。

```
Traceback (most recent call last):
  File "temp.py", line 77, in <module>
    model = vgg11(pretrained=True)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/flowvision/models/vgg.py", line 182, in vgg11
    return _vgg("vgg11", "A", False, pretrained, progress, **kwargs)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/flowvision/models/vgg.py", line 156, in _vgg
    state_dict = load_state_dict_from_url(model_urls[arch], progress=progress)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/flowvision/models/utils.py", line 146, in load_state_dict_from_url
    return _legacy_zip_load(cached_file, model_dir, map_location, delete_file)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/flowvision/models/utils.py", line 78, in _legacy_zip_load
    f.extractall(model_dir)
  File "/usr/local/miniconda3/lib/python3.7/zipfile.py", line 1636, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/usr/local/miniconda3/lib/python3.7/zipfile.py", line 1691, in _extract_member
    shutil.copyfileobj(source, target)
  File "/usr/local/miniconda3/lib/python3.7/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
  File "/usr/local/miniconda3/lib/python3.7/zipfile.py", line 930, in read
    data = self._read1(n)
  File "/usr/local/miniconda3/lib/python3.7/zipfile.py", line 1006, in _read1
    data = self._decompressor.decompress(data, n)
zlib.error: Error -2 while decompressing data: inconsistent stream state
```

**Comment by kaijieshi7** [comment]
代码看看，我这里没报错

**Comment by Alive1024** [comment]
```
from flowvision.models import vgg11

model = vgg11(pretrained=True)
```
![image](https://user-images.githubusercontent.com/46194306/156722774-545debcf-c594-48a1-b5ad-fe6bed84cad8.png)

**Comment by rentainhe** [comment]
可以把你目前遇到有问题的模型列一个list嘛，我们这边会一一查看并修复~

**Comment by kaijieshi7** [comment]
> 可以把你目前遇到有问题的模型列一个list嘛，我们这边会一一查看并修复~

应该不是权重的问题，他用的是docker，待会儿他把东西都放上来

**Comment by kaijieshi7** [comment]
一开始是有问题，用着用着又突然没问题了。
