### ISSUE TITLE
[feature] OneFlow和PyTorch兼容性测试

### ISSUE THREAD

**Issue by BBuf** [Oneflow-Inc/vision#185]
oneflow ci里面的兼容性测试框架：

https://github.com/Oneflow-Inc/oneflow/pull/6076

原理就是把pytorch实现的模型，直接`import oneflow as torch` run一次看是否存在bug以及Loss的差距是否比较大来测试兼容性。

本次任务需要完成flowvision所有的模型的兼容性测试，并且把所有不兼容的接口记录下来在0.8.0之前解决。

最后需要提供2个表格，分别是算子兼容性和模型兼容性，表格还需要调研一下写成什么样子。

后续会提供兼容测试的分工。

**Comment by ZiqiuChi** [comment]
**关于oneflow.nn.functional.conv2d的bug**

```
>>> flow.__version__
'0.7.0.dev20220224+cu112'
>>> torch.__version__
'1.10.2+cu102'
```
---

一些参数需要显式指定才行，而且会报`TypeError: conv2d(): missing required argument channel_pos`的bug，复现如下：

```
>>> from oneflow.nn.functional import conv2d
>>> img = flow.ones(1,3,224,224)
>>> kernel = flow.randn(3,1,3,3)
>>> conv2d(img, kernel, groups=3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
oneflow._oneflow_internal.exception.TypeException: 
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/api/python/functional/py_function.cpp", line 107, in ParseArgs
    TypeError: conv2d(): missing required argument stride
>>> conv2d(img, kernel, groups=3, stride=[1], padding=[0], dilation=[1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
oneflow._oneflow_internal.exception.TypeException: 
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/api/python/functional/py_function.cpp", line 107, in ParseArgs
    TypeError: conv2d(): missing required argument channel_pos
```

```
>>> from torch.nn.functional import conv2d
>>> img = torch.ones(1,3,224,224)
>>> kernel = torch.randn(3,1,3,3)
>>> conv2d(img, kernel, groups=3)
tensor([[[[-1.1668, -1.1668, -1.1668,  ..., -1.1668, -1.1668, -1.1668],
          [-1.1668, -1.1668, -1.1668,  ..., -1.1668, -1.1668, -1.1668],
          [-1.1668, -1.1668, -1.1668,  ..., -1.1668, -1.1668, -1.1668],
          ...,
          [-1.1668, -1.1668, -1.1668,  ..., -1.1668, -1.1668, -1.1668],
          [-1.1668, -1.1668, -1.1668,  ..., -1.1668, -1.1668, -1.1668],
          [-1.1668, -1.1668, -1.1668,  ..., -1.1668, -1.1668, -1.1668]],

         [[ 4.8856,  4.8856,  4.8856,  ...,  4.8856,  4.8856,  4.8856],
          [ 4.8856,  4.8856,  4.8856,  ...,  4.8856,  4.8856,  4.8856],
          [ 4.8856,  4.8856,  4.8856,  ...,  4.8856,  4.8856,  4.8856],
          ...,
          [ 4.8856,  4.8856,  4.8856,  ...,  4.8856,  4.8856,  4.8856],
          [ 4.8856,  4.8856,  4.8856,  ...,  4.8856,  4.8856,  4.8856],
          [ 4.8856,  4.8856,  4.8856,  ...,  4.8856,  4.8856,  4.8856]],

         [[-1.3948, -1.3948, -1.3948,  ..., -1.3948, -1.3948, -1.3948],
          [-1.3948, -1.3948, -1.3948,  ..., -1.3948, -1.3948, -1.3948],
          [-1.3948, -1.3948, -1.3948,  ..., -1.3948, -1.3948, -1.3948],
          ...,
          [-1.3948, -1.3948, -1.3948,  ..., -1.3948, -1.3948, -1.3948],
          [-1.3948, -1.3948, -1.3948,  ..., -1.3948, -1.3948, -1.3948],
          [-1.3948, -1.3948, -1.3948,  ..., -1.3948, -1.3948, -1.3948]]]])
```

**Comment by BBuf** [comment]
> **关于oneflow.nn.functional.conv2d的bug**
> 
> ```
> >>> flow.__version__
> '0.7.0.dev20220224+cu112'
> >>> torch.__version__
> '1.10.2+cu102'
> ```
> 
> 一些参数需要显式指定才行，而且会报`TypeError: conv2d(): missing required argument channel_pos`的bug，复现如下：
> 
> ```
> >>> from oneflow.nn.functional import conv2d
> >>> img = flow.ones(1,3,224,224)
> >>> kernel = flow.randn(3,1,3,3)
> >>> conv2d(img, kernel, groups=3)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> oneflow._oneflow_internal.exception.TypeException: 
>   File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/api/python/functional/py_function.cpp", line 107, in ParseArgs
>     TypeError: conv2d(): missing required argument stride
> >>> conv2d(img, kernel, groups=3, stride=[1], padding=[0], dilation=[1])
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> oneflow._oneflow_internal.exception.TypeException: 
>   File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/api/python/functional/py_function.cpp", line 107, in ParseArgs
>     TypeError: conv2d(): missing required argument channel_pos
> ```
> 
> ```
> >>> from torch.nn.functional import conv2d
> >>> img = torch.ones(1,3,224,224)
> >>> kernel = torch.randn(3,1,3,3)
> >>> conv2d(img, kernel, groups=3)
> tensor([[[[-1.1668, -1.1668, -1.1668,  ..., -1.1668, -1.1668, -1.1668],
>           [-1.1668, -1.1668, -1.1668,  ..., -1.1668, -1.1668, -1.1668],
>           [-1.1668, -1.1668, -1.1668,  ..., -1.1668, -1.1668, -1.1668],
>           ...,
>           [-1.1668, -1.1668, -1.1668,  ..., -1.1668, -1.1668, -1.1668],
>           [-1.1668, -1.1668, -1.1668,  ..., -1.1668, -1.1668, -1.1668],
>           [-1.1668, -1.1668, -1.1668,  ..., -1.1668, -1.1668, -1.1668]],
> 
>          [[ 4.8856,  4.8856,  4.8856,  ...,  4.8856,  4.8856,  4.8856],
>           [ 4.8856,  4.8856,  4.8856,  ...,  4.8856,  4.8856,  4.8856],
>           [ 4.8856,  4.8856,  4.8856,  ...,  4.8856,  4.8856,  4.8856],
>           ...,
>           [ 4.8856,  4.8856,  4.8856,  ...,  4.8856,  4.8856,  4.8856],
>           [ 4.8856,  4.8856,  4.8856,  ...,  4.8856,  4.8856,  4.8856],
>           [ 4.8856,  4.8856,  4.8856,  ...,  4.8856,  4.8856,  4.8856]],
> 
>          [[-1.3948, -1.3948, -1.3948,  ..., -1.3948, -1.3948, -1.3948],
>           [-1.3948, -1.3948, -1.3948,  ..., -1.3948, -1.3948, -1.3948],
>           [-1.3948, -1.3948, -1.3948,  ..., -1.3948, -1.3948, -1.3948],
>           ...,
>           [-1.3948, -1.3948, -1.3948,  ..., -1.3948, -1.3948, -1.3948],
>           [-1.3948, -1.3948, -1.3948,  ..., -1.3948, -1.3948, -1.3948],
>           [-1.3948, -1.3948, -1.3948,  ..., -1.3948, -1.3948, -1.3948]]]])
> ```

在这个pr里解决了：https://github.com/Oneflow-Inc/oneflow/pull/7892

**Comment by Ldpe2G** [comment]
https://github.com/Oneflow-Inc/OneTeam/issues/1271
